# Batak Toba-Indonesian machine translation

## Requirements

In [ ]:
# Transformers installation
# ! pip install transformers datasets evaluate sacrebleu tensorflow ipywidgets ipykernel transformers[torch] # If running Jupyter Notebook locally
! pip install transformers datasets==2.13.1 evaluate sacrebleu transformers[torch] # If running using Google Colab

# To install from source instead of the last release, comment the command above and uncomment the following one.
# ! pip install git+https://github.com/huggingface/transformers.git

Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.34.1)
Requirement already satisfied: datasets==2.13.1 in /usr/local/lib/python3.10/dist-packages (2.13.1)
Requirement already satisfied: evaluate in /usr/local/lib/python3.10/dist-packages (0.4.1)
Requirement already satisfied: sacrebleu in /usr/local/lib/python3.10/dist-packages (2.3.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from datasets==2.13.1) (1.23.5)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets==2.13.1) (9.0.0)
Requirement already satisfied: dill<0.3.7,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets==2.13.1) (0.3.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets==2.13.1) (1.5.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from datasets==2.13.1) (2.31.0)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from datasets==2.13.1) (4.66.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets==2.13.1) (3.4.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from datasets==2.13.1) (0.70.14)
Requirement already satisfied: fsspec[http]>=2021.11.1 in /usr/local/lib/python3.10/dist-packages (from datasets==2.13.1) (2023.6.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets==2.13.1) (3.8.6)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.11.0 in /usr/local/lib/python3.10/dist-packages (from datasets==2.13.1) (0.17.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets==2.13.1) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets==2.13.1) (6.0.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.12.4)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2023.6.3)
Requirement already satisfied: tokenizers<0.15,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.14.1)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.0)
Requirement already satisfied: responses<0.19 in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.18.0)
Requirement already satisfied: portalocker in /usr/local/lib/python3.10/dist-packages (from sacrebleu) (2.8.2)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.10/dist-packages (from sacrebleu) (0.9.0)
Requirement already satisfied: colorama in /usr/local/lib/python3.10/dist-packages (from sacrebleu) (0.4.6)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from sacrebleu) (4.9.3)
Requirement already satisfied: torch!=1.12.0,>=1.10 in /usr/local/lib/python3.10/dist-packages (from transformers) (2.1.0+cu118)
Requirement already satisfied: accelerate>=0.20.3 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate>=0.20.3->transformers) (5.9.5)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets==2.13.1) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets==2.13.1) (3.3.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets==2.13.1) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets==2.13.1) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets==2.13.1) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets==2.13.1) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets==2.13.1) (1.3.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0.0,>=0.11.0->datasets==2.13.1) (4.5.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets==2.13.1) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets==2.13.1) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets==2.13.1) (2023.7.22)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch!=1.12.0,>=1.10->transformers) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch!=1.12.0,>=1.10->transformers) (3.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch!=1.12.0,>=1.10->transformers) (3.1.2)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch!=1.12.0,>=1.10->transformers) (2.1.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets==2.13.1) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets==2.13.1) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->datasets==2.13.1) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch!=1.12.0,>=1.10->transformers) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch!=1.12.0,>=1.10->transformers) (1.3.0)

In [ ]:
# from huggingface_hub import notebook_login
# notebook_login()

from huggingface_hub import login
login(token="YOUR_HF_TOKEN_HERE")

Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /root/.cache/huggingface/token
Login successful

In [ ]:
# To be able to use indonlp/nusatranslation_mt, you need to install the following dependency: nusacrowd
! pip install nusacrowd

Requirement already satisfied: nusacrowd in /usr/local/lib/python3.10/dist-packages (0.1.2)
Requirement already satisfied: loguru>=0.5.3 in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (0.7.2)
Requirement already satisfied: bioc>=1.3.7 in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (2.1)
Requirement already satisfied: pandas>=1.3.3 in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (1.5.3)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (1.23.5)
Requirement already satisfied: datasets>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (2.13.1)
Requirement already satisfied: black~=22.0 in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (22.12.0)
Requirement already satisfied: flake8>=3.8.3 in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (6.1.0)
Requirement already satisfied: isort>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (5.12.0)
Requirement already satisfied: aiohttp>=3.8.1 in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (3.8.6)
Requirement already satisfied: pre-commit>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (3.5.0)
Requirement already satisfied: jsonlines>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (4.0.0)
Requirement already satisfied: torchaudio>=0.11 in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (2.1.0+cu118)
Requirement already satisfied: soundfile in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (0.12.1)
Requirement already satisfied: librosa in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (0.10.1)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (3.8.1)
Requirement already satisfied: zstandard in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (0.21.0)
Requirement already satisfied: ffmpeg in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (1.4)
Requirement already satisfied: conllu in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (4.5.3)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (3.1.2)
Requirement already satisfied: translate-toolkit>=3.7.3 in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (3.10.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from nusacrowd) (4.5.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp>=3.8.1->nusacrowd) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp>=3.8.1->nusacrowd) (3.3.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp>=3.8.1->nusacrowd) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.10/dist-packages (from aiohttp>=3.8.1->nusacrowd) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp>=3.8.1->nusacrowd) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp>=3.8.1->nusacrowd) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp>=3.8.1->nusacrowd) (1.3.1)
Requirement already satisfied: lxml>=4.6.3 in /usr/local/lib/python3.10/dist-packages (from bioc>=1.3.7->nusacrowd) (4.9.3)
Requirement already satisfied: intervaltree in /usr/local/lib/python3.10/dist-packages (from bioc>=1.3.7->nusacrowd) (3.1.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from bioc>=1.3.7->nusacrowd) (4.66.1)
Requirement already satisfied: docopt in /usr/local/lib/python3.10/dist-packages (from bioc>=1.3.7->nusacrowd) (0.6.2)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from black~=22.0->nusacrowd) (8.1.7)
Requirement already satisfied: mypy-extensions>=0.4.3 in /usr/local/lib/python3.10/dist-packages (from black~=22.0->nusacrowd) (1.0.0)
Requirement already satisfied: pathspec>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from black~=22.0->nusacrowd) (0.11.2)
Requirement already satisfied: platformdirs>=2 in /usr/local/lib/python3.10/dist-packages (from black~=22.0->nusacrowd) (3.11.0)
Requirement already satisfied: tomli>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from black~=22.0->nusacrowd) (2.0.1)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.2.0->nusacrowd) (9.0.0)
Requirement already satisfied: dill<0.3.7,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.2.0->nusacrowd) (0.3.6)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.2.0->nusacrowd) (2.31.0)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets>=2.2.0->nusacrowd) (3.4.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from datasets>=2.2.0->nusacrowd) (0.70.14)
Requirement already satisfied: fsspec[http]>=2021.11.1 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.2.0->nusacrowd) (2023.6.0)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.11.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.2.0->nusacrowd) (0.17.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets>=2.2.0->nusacrowd) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.2.0->nusacrowd) (6.0.1)
Requirement already satisfied: mccabe<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from flake8>=3.8.3->nusacrowd) (0.7.0)
Requirement already satisfied: pycodestyle<2.12.0,>=2.11.0 in /usr/local/lib/python3.10/dist-packages (from flake8>=3.8.3->nusacrowd) (2.11.1)
Requirement already satisfied: pyflakes<3.2.0,>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from flake8>=3.8.3->nusacrowd) (3.1.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.3->nusacrowd) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.3->nusacrowd) (2023.3.post1)
Requirement already satisfied: cfgv>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from pre-commit>=2.19.0->nusacrowd) (3.4.0)
Requirement already satisfied: identify>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from pre-commit>=2.19.0->nusacrowd) (2.5.30)
Requirement already satisfied: nodeenv>=0.11.1 in /usr/local/lib/python3.10/dist-packages (from pre-commit>=2.19.0->nusacrowd) (1.8.0)
Requirement already satisfied: virtualenv>=20.10.0 in /usr/local/lib/python3.10/dist-packages (from pre-commit>=2.19.0->nusacrowd) (20.24.6)
Requirement already satisfied: torch==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torchaudio>=0.11->nusacrowd) (2.1.0+cu118)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch==2.1.0->torchaudio>=0.11->nusacrowd) (3.12.4)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch==2.1.0->torchaudio>=0.11->nusacrowd) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch==2.1.0->torchaudio>=0.11->nusacrowd) (3.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch==2.1.0->torchaudio>=0.11->nusacrowd) (3.1.2)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch==2.1.0->torchaudio>=0.11->nusacrowd) (2.1.0)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.10/dist-packages (from librosa->nusacrowd) (3.0.1)
Requirement already satisfied: scipy>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from librosa->nusacrowd) (1.11.3)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from librosa->nusacrowd) (1.2.2)
Requirement already satisfied: joblib>=0.14 in /usr/local/lib/python3.10/dist-packages (from librosa->nusacrowd) (1.3.2)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from librosa->nusacrowd) (4.4.2)
Requirement already satisfied: numba>=0.51.0 in /usr/local/lib/python3.10/dist-packages (from librosa->nusacrowd) (0.56.4)
Requirement already satisfied: pooch>=1.0 in /usr/local/lib/python3.10/dist-packages (from librosa->nusacrowd) (1.8.0)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.10/dist-packages (from librosa->nusacrowd) (0.3.7)
Requirement already satisfied: lazy-loader>=0.1 in /usr/local/lib/python3.10/dist-packages (from librosa->nusacrowd) (0.3)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.10/dist-packages (from librosa->nusacrowd) (1.0.7)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.10/dist-packages (from soundfile->nusacrowd) (1.16.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk->nusacrowd) (2023.6.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl->nusacrowd) (1.1.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.0->soundfile->nusacrowd) (2.21)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from nodeenv>=0.11.1->pre-commit>=2.19.0->nusacrowd) (67.7.2)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba>=0.51.0->librosa->nusacrowd) (0.39.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=1.3.3->nusacrowd) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets>=2.2.0->nusacrowd) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets>=2.2.0->nusacrowd) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets>=2.2.0->nusacrowd) (2023.7.22)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->librosa->nusacrowd) (3.2.0)
Requirement already satisfied: distlib<1,>=0.3.7 in /usr/local/lib/python3.10/dist-packages (from virtualenv>=20.10.0->pre-commit>=2.19.0->nusacrowd) (0.3.7)
Requirement already satisfied: sortedcontainers<3.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from intervaltree->bioc>=1.3.7->nusacrowd) (2.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch==2.1.0->torchaudio>=0.11->nusacrowd) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch==2.1.0->torchaudio>=0.11->nusacrowd) (1.3.0)

## 1. Batak Toba to Indonesian

In [ ]:
from datasets import load_dataset

# Load the dataset from Hugging Face Datasets
dataset_btk_to_ind = load_dataset("indonlp/nusatranslation_mt", "nusatranslation_mt_btk_ind_source")

WARNING:datasets.builder:Found cached dataset nusatranslation_mt (/root/.cache/huggingface/datasets/indonlp___nusatranslation_mt/nusatranslation_mt_btk_ind_source/1.0.0/7bc55ca0431a2e37367c37eaadf3eb41305c25f22713b09932865f27d6b4c005)

  0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
dataset_btk_to_ind['train'][0]

{'id': '0',
 'text': 'hobi doma mangua? ? selfie , rap mar hp wkw marsiajar juo sih  tai inda na jotjot tu wkw http://ask.fm/a/c0dmqfll',
 'label': 'hobi banget ngapain? ? selfie , sama mainan hp wkw belajar juga sih tapi gak keseringan bgt wkw http://ask.fm/a/c0dmqfll'}

In [ ]:
# Rename 'text' to 'source' and 'label' to 'target' in the dataset
dataset_btk_to_ind = dataset_btk_to_ind.rename_column("text", "source")
dataset_btk_to_ind = dataset_btk_to_ind.rename_column("label", "target")

In [ ]:
# Verify the column names
dataset_btk_to_ind['train'][0]

{'id': '0',
 'source': 'hobi doma mangua? ? selfie , rap mar hp wkw marsiajar juo sih  tai inda na jotjot tu wkw http://ask.fm/a/c0dmqfll',
 'target': 'hobi banget ngapain? ? selfie , sama mainan hp wkw belajar juga sih tapi gak keseringan bgt wkw http://ask.fm/a/c0dmqfll'}

### Data preparation

The next step is to load a T5 tokenizer to process the Batak Toba-Indonesian language pairs:

In [ ]:
! pip install sentencepiece # For Facebook's NLLB models

Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (0.1.99)

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("facebook/nllb-200-distilled-600M", use_auth_token=True, src_lang="btk_Latn", tgt_lang="ind_Latn")
# List of supported languages: https://github.com/facebookresearch/flores/tree/main/flores200#languages-in-flores-200

/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py:655: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(

In [ ]:
# source_lang = "ind_text"
# target_lang = "tgt_text"
# prefix = "translate Batak Toba to Indonesian: " # Prefix is for T5 pre-trained model. See: https://huggingface.co/docs/transformers/v4.34.0/en/model_doc/t5#t5

def preprocess_function(examples): # THIS WORKS
    # inputs = [prefix + example for example in examples["source"]] # Prefix is for T5 pre-trained model.
    inputs = [example for example in examples["source"]]
    targets = [example for example in examples["target"]]

    model_inputs = tokenizer(inputs, text_target=targets, max_length=64, padding="max_length", truncation=True, return_tensors="pt")
    return model_inputs

# speed up the map function by setting batched=True to process multiple elements of the dataset at once
tokenized_dataset = dataset_btk_to_ind.map(preprocess_function, batched=True, remove_columns=["id", "source", "target"])

WARNING:datasets.arrow_dataset:Loading cached processed dataset at /root/.cache/huggingface/datasets/indonlp___nusatranslation_mt/nusatranslation_mt_btk_ind_source/1.0.0/7bc55ca0431a2e37367c37eaadf3eb41305c25f22713b09932865f27d6b4c005/cache-87f627dd5d94f848.arrow

Map:   0%|          | 0/849 [00:00<?, ? examples/s]

WARNING:datasets.arrow_dataset:Loading cached processed dataset at /root/.cache/huggingface/datasets/indonlp___nusatranslation_mt/nusatranslation_mt_btk_ind_source/1.0.0/7bc55ca0431a2e37367c37eaadf3eb41305c25f22713b09932865f27d6b4c005/cache-039e6156db515c98.arrow

In [ ]:
tokenized_dataset["train"][0]

{'input_ids': [3,
  173979,
  20557,
  1990,
  253,
  248130,
  385,
  227591,
  146,
  4713,
  675,
  21690,
  66780,
  675,
  28696,
  2686,
  45836,
  17745,
  3969,
  17186,
  62,
  12131,
  53937,
  334,
  66780,
  138443,
  83853,
  44788,
  248075,
  248090,
  248070,
  248504,
  248060,
  248504,
  248080,
  248141,
  248072,
  248070,
  248136,
  248090,
  1015,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'labels': [256075,
  173979,
  10607,
  122774,
  248130,
  385,
  227591,
  146,
  3000,
  196574,
  21690,
  66780,
  26819,
  5083,
  17745,
  4141,
  8075,
  2774,
  5334,
  4,
  82524,
  66780,
  138443,
  83853,
  44788,
  248075,
  248090,
  248070,
  248504,
  248060,
  248504,
  248080,
  248141,
  248072,
  248070,
  248136,
  248090,
  1015,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1]}

In [ ]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model="facebook/nllb-200-distilled-600M")

### Assessment

In [ ]:
import evaluate

metric = evaluate.load("sacrebleu")

In [ ]:
import numpy as np

def postprocess_text(preds, labels):
    preds = [pred.strip() for pred in preds]
    labels = [[label.strip()] for label in labels]

    return preds, labels


def compute_metrics(eval_preds):
    preds, labels = eval_preds
    if isinstance(preds, tuple):
        preds = preds[0]
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)

    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    decoded_preds, decoded_labels = postprocess_text(decoded_preds, decoded_labels)

    result = metric.compute(predictions=decoded_preds, references=decoded_labels)
    result = {"sacrebleu": result["score"]}

    prediction_lens = [np.count_nonzero(pred != tokenizer.pad_token_id) for pred in preds]
    result["gen_len"] = np.mean(prediction_lens)
    result = {k: round(v, 4) for k, v in result.items()}
    return result

### Model training

In [ ]:
from transformers import AutoModelForSeq2SeqLM

model = AutoModelForSeq2SeqLM.from_pretrained("facebook/nllb-200-distilled-600M", use_auth_token=True)

/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py:472: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py:374: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(

### Assessing the NLLB model **before/pre** fine-tuning (without training on the Batak Toba dataset)

In [ ]:
from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainer, Seq2SeqTrainingArguments

training_args = Seq2SeqTrainingArguments(
    output_dir="batak_toba_to_indonesian_translation_model",
    evaluation_strategy="epoch",
    per_device_eval_batch_size=16,

    # For optimizing resources usage (GPU, RAM, etc.)
    # ---
    predict_with_generate=True,
    optim="adamw_bnb_8bit",
    fp16=True,
    push_to_hub=True,
    save_total_limit=3,
    eval_accumulation_steps=4,
)

# Create a Seq2SeqTrainer for evaluation only
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=None,  # Set train_dataset to None for evaluation
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.evaluate(eval_dataset=tokenized_dataset["test"])

You're using a NllbTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

{'eval_loss': 7.952581882476807,
 'eval_sacrebleu': 11.4161,
 'eval_gen_len': 52.73,
 'eval_runtime': 589.5882,
 'eval_samples_per_second': 3.392,
 'eval_steps_per_second': 0.212}

In [ ]:
from transformers import pipeline
import evaluate

metric = evaluate.load("sacrebleu")
translator = pipeline("translation", model="facebook/nllb-200-distilled-600M")

test_sentences = {
    "text1": {"source": "Adong na boi hu urupi?", "target": "Ada yang bisa aku bantu?"},
    "text2": {
        "source": "Ubat ni sude sahit roha na sonang.",
        "target": "Obat segala penyakit adalah hati yang gembira.",
    },
    "text3": {
        "source": "Teratur mangan dohot cukup parmodom mu dah, asa unang marsahit be muse.",
        "target": "Makan teratur dan istirahat yang cukup ya, biar ga sakit lagi.",
    },
    "text4": {
        "source": "Jolma na tarbereng sonang dijoloni natorop, dang tentu jolma naso adong masalahna, alai ima jolma na tangis disihabunian.",
        "target": "Orang yang bahagia di depan orang banyak, bukanlah orang yang tidak punya masalah, tetapi dialah orang yang menangis dikala orang tidak ada.",
    },
    "text5": {
        "source": "Ale Tuhan, lean ma hasabaron tu keluarga na dibagas parmaraan. Alana takkas do huboto nami, sude na marhosa dohot na manggulmit di portibi on to saat tujoloMu do ujungna. Anggiat ma Ho ale Jahowa manjalo toddi ni keluarga nami on, sahat ro di tanganMu ma ibana, jala pahuddul ma i di inganan na sonang.",
        "target": "Ya Tuhan, tabahkanlah keluarga yang sedang dilanda musibah. Karena, semua makhluk di dunia pasti akan ada saatnya menemui Sang Pencipta. Semoga Engkau menerima arwah saudara kami dengan tanganMu yang terbuka lebar menyambutnya dan menempatkannya di tempat yang terindah.",
    },
}

translated_sentences = []

# Perform translation and evaluation for each test sentence
for key, text_dict in test_sentences.items():
    source_text, translation, correct_translation = text_dict["source"], "", text_dict["target"]

    # Translate the source text
    translated_text = translator(source_text, src_lang="btk_Latn", tgt_lang="ind_Latn")
    translation = translated_text[0]["translation_text"]

    # Calculate the SacreBLEU score
    sacrebleu_score = metric.compute(predictions=[translation], references=[[correct_translation]])
    sacrebleu_score = sacrebleu_score["score"]

    translated_sentences.append((source_text, translation, correct_translation, sacrebleu_score))

# Print the results
for i, (source, translation, correct_translation, sacrebleu_score) in enumerate(translated_sentences):
    print(f"Sentence {i + 1}:")
    print("Source Sentence: ", source)
    print("Translated Sentence: ", translation)
    print("Correct Translated Sentence: ", correct_translation)
    print("SacreBLEU Score: ", sacrebleu_score)
    print()

Sentence 1:
Source Sentence:  Adong na boi hu urupi?
Translated Sentence:  Apakah Anda takut dengan organisasi?
Correct Translated Sentence:  Ada yang bisa aku bantu?
SacreBLEU Score:  8.116697886877475

Sentence 2:
Source Sentence:  Ubat ni sude sahit roha na sonang.
Translated Sentence:  Ubat adalah bagian selatan dari sahit roha dan sonang.
Correct Translated Sentence:  Obat segala penyakit adalah hati yang gembira.
SacreBLEU Score:  4.990049701936832

Sentence 3:
Source Sentence:  Teratur mangan dohot cukup parmodom mu dah, asa unang marsahit be muse.
Translated Sentence:  Teratur mangan dohot cukup parmodom mu dah, asa unang marsahit menjadi muse.
Correct Translated Sentence:  Makan teratur dan istirahat yang cukup ya, biar ga sakit lagi.
SacreBLEU Score:  3.737437943747671

Sentence 4:
Source Sentence:  Jolma na tarbereng sonang dijoloni natorop, dang tentu jolma naso adong masalahna, alai ima jolma na tangis disihabunian.
Translated Sentence:  Jolma dan tarbereng sonang dijoloni natorop, dang tentu jolma naso adong masalahna, alai ima jolma dan tangis disihabunian.
Correct Translated Sentence:  Orang yang bahagia di depan orang banyak, bukanlah orang yang tidak punya masalah, tetapi dialah orang yang menangis dikala orang tidak ada.
SacreBLEU Score:  1.9755758683310292

Sentence 5:
Source Sentence:  Ale Tuhan, lean ma hasabaron tu keluarga na dibagas parmaraan. Alana takkas do huboto nami, sude na marhosa dohot na manggulmit di portibi on to saat tujoloMu do ujungna. Anggiat ma Ho ale Jahowa manjalo toddi ni keluarga nami on, sahat ro di tanganMu ma ibana, jala pahuddul ma i di inganan na sonang.
Translated Sentence:  Ya Tuhan, lean ma hasabaron tu keluarga dan dibagas parmaraan. Alana takkas do huboto denganku, selatan dan marhosa dohot dan manggulmit di portibi pada saat itu aku pergi ke mu akhirna. Anggiat ma ho ale jehova dan keluarga ku pada saat ini, sahat kami berada di tanganMu dan ibana, jala pahuddul dan di sini sama dengan sonang.
Correct Translated Sentence:  Ya Tuhan, tabahkanlah keluarga yang sedang dilanda musibah. Karena, semua makhluk di dunia pasti akan ada saatnya menemui Sang Pencipta. Semoga Engkau menerima arwah saudara kami dengan tanganMu yang terbuka lebar menyambutnya dan menempatkannya di tempat yang terindah.
SacreBLEU Score:  3.09543363217725

In [ ]:
import locale
locale.getpreferredencoding = lambda: "UTF-8"

In [ ]:
! pip install bitsandbytes # For 'adamw_bnb_8bit' optimizer

Collecting bitsandbytes
  Downloading bitsandbytes-0.41.1-py3-none-any.whl (92.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.6/92.6 MB 13.6 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.41.1

In [ ]:
model

M2M100ForConditionalGeneration(
  (model): M2M100Model(
    (shared): Embedding(256206, 1024, padding_idx=1)
    (encoder): M2M100Encoder(
      (embed_tokens): Embedding(256206, 1024, padding_idx=1)
      (embed_positions): M2M100SinusoidalPositionalEmbedding()
      (layers): ModuleList(
        (0-11): 12 x M2M100EncoderLayer(
          (self_attn): M2M100Attention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (activation_fn): ReLU()
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
    (decoder): M2M100Decoder(
      (embed_tokens): Embedding(256206, 1024, padding_idx=1)
      (embed_positions): M2M100SinusoidalPositionalEmbedding()
      (layers): ModuleList(
        (0-11): 12 x M2M100DecoderLayer(
          (self_attn): M2M100Attention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (activation_fn): ReLU()
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (encoder_attn): M2M100Attention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (encoder_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
  )
  (lm_head): Linear(in_features=1024, out_features=256206, bias=False)
)

In [ ]:
from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer

training_args = Seq2SeqTrainingArguments(
    output_dir="batak_toba_to_indonesian_translation_model",
    evaluation_strategy="epoch",

    # Parameters to tune
    # ---
    learning_rate=5e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=16,
    weight_decay=0.3,
    num_train_epochs=5,
    warmup_ratio=0.1,
    # ---

    # For optimizing resources usage (GPU, RAM, etc.)
    # ---
    predict_with_generate=True,
    optim="adamw_bnb_8bit",
    fp16=True,
    push_to_hub=True,
    save_total_limit=3,
    eval_accumulation_steps=4,
    # ---
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.train()

TrainOutput(global_step=8250, training_loss=1.2929620361328125, metrics={'train_runtime': 6375.4494, 'train_samples_per_second': 5.176, 'train_steps_per_second': 1.294, 'total_flos': 4469653241856000.0, 'train_loss': 1.2929620361328125, 'epoch': 5.0})

In [ ]:
trainer.push_to_hub()

pytorch_model.bin:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

'https://huggingface.co/kepinsam/bataknese_to_indonesian_translation_model/tree/main/'

### Assessing the NLLB model **after/post** fine-tuning (with training on the Batak Toba dataset)

In [ ]:
from transformers import pipeline
import evaluate

translator = pipeline("translation", model="batak_toba_to_indonesian_translation_model")
metric = evaluate.load("sacrebleu")

test_sentences = {
    "text1": {
        "source": "Adong na boi hu urupi?",
        "target": "Ada yang bisa aku bantu?"
        },
    "text2": {
        "source": "Ubat ni sude sahit roha na sonang.",
        "target": "Obat segala penyakit adalah hati yang gembira.",
    },
    "text3": {
        "source": "Teratur mangan dohot cukup parmodom mu dah, asa unang marsahit be muse.",
        "target": "Makan teratur dan istirahat yang cukup ya, biar ga sakit lagi.",
    },
    "text4": {
        "source": "Jolma na tarbereng sonang dijoloni natorop, dang tentu jolma naso adong masalahna, alai ima jolma na tangis disihabunian.",
        "target": "Orang yang bahagia di depan orang banyak, bukanlah orang yang tidak punya masalah, tetapi dialah orang yang menangis dikala orang tidak ada.",
    },
    "text5": {
        "source": "Ale Tuhan, lean ma hasabaron tu keluarga na dibagas parmaraan. Alana takkas do huboto nami, sude na marhosa dohot na manggulmit di portibi on to saat tujoloMu do ujungna. Anggiat ma Ho ale Jahowa manjalo toddi ni keluarga nami on, sahat ro di tanganMu ma ibana, jala pahuddul ma i di inganan na sonang.",
        "target": "Ya Tuhan, tabahkanlah keluarga yang sedang dilanda musibah. Karena, semua makhluk di dunia pasti akan ada saatnya menemui Sang Pencipta. Semoga Engkau menerima arwah saudara kami dengan tanganMu yang terbuka lebar menyambutnya dan menempatkannya di tempat yang terindah.",
    },
}

translated_sentences = []

# Perform translation and evaluation for each test sentence
for key, text_dict in test_sentences.items():
    source_text, translation, correct_translation = text_dict["source"], "", text_dict["target"]

    # Translate the source text
    translated_text = translator(source_text, src_lang="btk_Latn", tgt_lang="ind_Latn")
    translation = translated_text[0]["translation_text"]

    # Calculate the SacreBLEU score
    sacrebleu_score = metric.compute(predictions=[translation], references=[[correct_translation]])
    sacrebleu_score = sacrebleu_score["score"]

    translated_sentences.append((source_text, translation, correct_translation, sacrebleu_score))

# Print the results
for i, (source, translation, correct_translation, sacrebleu_score) in enumerate(translated_sentences):
    print(f"Sentence {i + 1}:")
    print("Source Sentence: ", source)
    print("Translated Sentence: ", translation)
    print("Correct Translated Sentence: ", correct_translation)
    print("SacreBLEU Score: ", sacrebleu_score)
    print()

Sentence 1:
Source Sentence:  Adong na boi hu urupi?
Translated Sentence:  Ada yang bisa saya bantu?
Correct Translated Sentence:  Ada yang bisa aku bantu?
SacreBLEU Score:  37.99178428257963

Sentence 2:
Source Sentence:  Ubat ni sude sahit roha na sonang.
Translated Sentence:  obat semua sakit hati yg menyenangkan.
Correct Translated Sentence:  Obat segala penyakit adalah hati yang gembira.
SacreBLEU Score:  6.770186228657864

Sentence 3:
Source Sentence:  Teratur mangan dohot cukup parmodom mu dah, asa unang marsahit be muse.
Translated Sentence:  Teratur makan dan cukup kamar anda ya, untuk tidak sakit lagi.
Correct Translated Sentence:  Makan teratur dan istirahat yang cukup ya, biar ga sakit lagi.
SacreBLEU Score:  15.727800941615351

Sentence 4:
Source Sentence:  Jolma na tarbereng sonang dijoloni natorop, dang tentu jolma naso adong masalahna, alai ima jolma na tangis disihabunian.
Translated Sentence:  Orang yang terlihat bahagia di sekitarnya, bukan tentu orang yang tidak punya masalah, tapi adalah orang yang menangis disebuah rumah.
Correct Translated Sentence:  Orang yang bahagia di depan orang banyak, bukanlah orang yang tidak punya masalah, tetapi dialah orang yang menangis dikala orang tidak ada.
SacreBLEU Score:  28.64122358136574

Sentence 5:
Source Sentence:  Ale Tuhan, lean ma hasabaron tu keluarga na dibagas parmaraan. Alana takkas do huboto nami, sude na marhosa dohot na manggulmit di portibi on to saat tujoloMu do ujungna. Anggiat ma Ho ale Jahowa manjalo toddi ni keluarga nami on, sahat ro di tanganMu ma ibana, jala pahuddul ma i di inganan na sonang.
Translated Sentence:  Ya Tuhan, berilah kesabaran kepada keluarga yang berada di dalam surga. Karena kami pasti tahu, bahwa semua yang berdosa dan bercita-cita di dunia akan datang menjelangMu pada akhirnya. Semoga Engkau tetapi juga Ya Allah menerima doa keluarga kami, sampai mereka datang ke tanganMu, dan memelukmu di tempat yang indah.
Correct Translated Sentence:  Ya Tuhan, tabahkanlah keluarga yang sedang dilanda musibah. Karena, semua makhluk di dunia pasti akan ada saatnya menemui Sang Pencipta. Semoga Engkau menerima arwah saudara kami dengan tanganMu yang terbuka lebar menyambutnya dan menempatkannya di tempat yang terindah.
SacreBLEU Score:  7.866170540941854

## 2. Indonesian to Batak Toba

In [ ]:
from datasets import load_dataset

# Load the dataset from Hugging Face Datasets
dataset_ind_to_btk = load_dataset("indonlp/nusatranslation_mt", "nusatranslation_mt_btk_ind_source")

WARNING:datasets.builder:Found cached dataset nusatranslation_mt (/root/.cache/huggingface/datasets/indonlp___nusatranslation_mt/nusatranslation_mt_btk_ind_source/1.0.0/7bc55ca0431a2e37367c37eaadf3eb41305c25f22713b09932865f27d6b4c005)

  0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
dataset_ind_to_btk['train'][0]

{'id': '0',
 'text': 'hobi doma mangua? ? selfie , rap mar hp wkw marsiajar juo sih  tai inda na jotjot tu wkw http://ask.fm/a/c0dmqfll',
 'label': 'hobi banget ngapain? ? selfie , sama mainan hp wkw belajar juga sih tapi gak keseringan bgt wkw http://ask.fm/a/c0dmqfll'}

In [ ]:
# Rename 'label' to 'source' and 'text' to 'target' in the dataset
dataset_ind_to_btk = dataset_ind_to_btk.rename_column("label", "source")
dataset_ind_to_btk = dataset_ind_to_btk.rename_column("text", "target")

In [ ]:
# Verify the column names
dataset_ind_to_btk['train'][0]

{'id': '0',
 'target': 'hobi doma mangua? ? selfie , rap mar hp wkw marsiajar juo sih  tai inda na jotjot tu wkw http://ask.fm/a/c0dmqfll',
 'source': 'hobi banget ngapain? ? selfie , sama mainan hp wkw belajar juga sih tapi gak keseringan bgt wkw http://ask.fm/a/c0dmqfll'}

### Data preparation

The next step is to load a T5 tokenizer to process the Batak Toba-Indonesian language pairs:

In [ ]:
! pip install sentencepiece # For Facebook's NLLB models

Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (0.1.99)

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("facebook/nllb-200-distilled-600M", use_auth_token=True, src_lang="ind_Latn", tgt_lang="btk_Latn")
# List of supported languages: https://github.com/facebookresearch/flores/tree/main/flores200#languages-in-flores-200

/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py:655: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(

In [ ]:
# source_lang = "ind_text"
# target_lang = "tgt_text"
# prefix = "translate Batak Toba to Indonesian: " # Prefix is for T5 pre-trained model. See: https://huggingface.co/docs/transformers/v4.34.0/en/model_doc/t5#t5

def preprocess_function(examples): # THIS WORKS
    # inputs = [prefix + example for example in examples["source"]] # Prefix is for T5 pre-trained model.
    inputs = [example for example in examples["source"]]
    targets = [example for example in examples["target"]]

    model_inputs = tokenizer(inputs, text_target=targets, max_length=64, padding="max_length", truncation=True, return_tensors="pt")
    return model_inputs

# speed up the map function by setting batched=True to process multiple elements of the dataset at once
tokenized_dataset = dataset_ind_to_btk.map(preprocess_function, batched=True, remove_columns=["id", "source", "target"])

WARNING:datasets.arrow_dataset:Loading cached processed dataset at /root/.cache/huggingface/datasets/indonlp___nusatranslation_mt/nusatranslation_mt_btk_ind_source/1.0.0/7bc55ca0431a2e37367c37eaadf3eb41305c25f22713b09932865f27d6b4c005/cache-a5e183272d1e5384.arrow

Map:   0%|          | 0/849 [00:00<?, ? examples/s]

WARNING:datasets.arrow_dataset:Loading cached processed dataset at /root/.cache/huggingface/datasets/indonlp___nusatranslation_mt/nusatranslation_mt_btk_ind_source/1.0.0/7bc55ca0431a2e37367c37eaadf3eb41305c25f22713b09932865f27d6b4c005/cache-650493cb2c31079d.arrow

In [ ]:
tokenized_dataset["train"][0]

{'input_ids': [256075,
  173979,
  10607,
  122774,
  248130,
  385,
  227591,
  146,
  3000,
  196574,
  21690,
  66780,
  26819,
  5083,
  17745,
  4141,
  8075,
  2774,
  5334,
  4,
  82524,
  66780,
  138443,
  83853,
  44788,
  248075,
  248090,
  248070,
  248504,
  248060,
  248504,
  248080,
  248141,
  248072,
  248070,
  248136,
  248090,
  1015,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'labels': [3,
  173979,
  20557,
  1990,
  253,
  248130,
  385,
  227591,
  146,
  4713,
  675,
  21690,
  66780,
  675,
  28696,
  2686,
  45836,
  17745,
  3969,
  17186,
  62,
  12131,
  53937,
  334,
  66780,
  138443,
  83853,
  44788,
  248075,
  248090,
  248070,
  248504,
  248060,
  248504,
  248080,
  248141,
  248072,
  248070,
  248136,
  248090,
  1015,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1]}

In [ ]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model="facebook/nllb-200-distilled-600M")

### Assessment

In [ ]:
import evaluate

metric = evaluate.load("sacrebleu")

In [ ]:
import numpy as np

def postprocess_text(preds, labels):
    preds = [pred.strip() for pred in preds]
    labels = [[label.strip()] for label in labels]

    return preds, labels


def compute_metrics(eval_preds):
    preds, labels = eval_preds
    if isinstance(preds, tuple):
        preds = preds[0]
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)

    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    decoded_preds, decoded_labels = postprocess_text(decoded_preds, decoded_labels)

    result = metric.compute(predictions=decoded_preds, references=decoded_labels)
    result = {"sacrebleu": result["score"]}

    prediction_lens = [np.count_nonzero(pred != tokenizer.pad_token_id) for pred in preds]
    result["gen_len"] = np.mean(prediction_lens)
    result = {k: round(v, 4) for k, v in result.items()}
    return result

### Model training

In [ ]:
from transformers import AutoModelForSeq2SeqLM

model = AutoModelForSeq2SeqLM.from_pretrained("facebook/nllb-200-distilled-600M", use_auth_token=True)

/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py:472: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py:374: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(

### Assessing the NLLB model **before/pre** fine-tuning (without training on the Batak Toba dataset)

In [ ]:
from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainer, Seq2SeqTrainingArguments

training_args = Seq2SeqTrainingArguments(
    output_dir="indonesian_to_batak_toba_translation_model",
    evaluation_strategy="epoch",
    per_device_eval_batch_size=8,

    # For optimizing resources usage (GPU, RAM, etc.)
    # ---
    predict_with_generate=True,
    optim="adamw_bnb_8bit",
    fp16=True,
    push_to_hub=True,
    save_total_limit=3,
    eval_accumulation_steps=4,
)

# Create a Seq2SeqTrainer for evaluation only
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=None,  # Set train_dataset to None for evaluation
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.evaluate(eval_dataset=tokenized_dataset["test"])

You're using a NllbTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

{'eval_loss': 8.374671936035156,
 'eval_sacrebleu': 5.016,
 'eval_gen_len': 34.9475,
 'eval_runtime': 631.3011,
 'eval_samples_per_second': 3.168,
 'eval_steps_per_second': 0.396}

In [ ]:
from transformers import pipeline
import evaluate

metric = evaluate.load("sacrebleu")
translator = pipeline("translation", model="facebook/nllb-200-distilled-600M")

test_sentences = {
    "text1": {
        "source": "Turun disini lah kita.",
        "target": "Turun dison ma hita.",
        },
    "text2": {
        "source": "Ini pengalaman pertamaku.",
        "target": "On ma pengalamanku na parjolo.",
    },
    "text3": {
        "source": "Jika kamu pergi, hatiku akan pergi bersamamu.",
        "target": "Molo lao ho, rohakku dohot mai lao.",
    },
    "text4": {
        "source": "Ketika menghadapi masalah apapun dalam kehidupan ini maka terimalah dengan hati yang sabar dan iman yang kuat.",
        "target": "Bahenma dirimu songon laut naluas , manang songon dia pe masalah naroh tungolumu, jalo ma dohot roha naserep dohot iman na gogo.",
    },
    "text5": {
        "source": "Biarlah orang lain memuji engkau dan bukan mulutmu, orang yang tidak kau kenal dan bukan bibirmu sendiri. Batu adalah berat dan pasir pun ada beratnya, tetapi lebih berat dari kedua-duanya adalah sakit hati terhadap orang bodoh.",
        "target": "Halak na asing tagonan mamuji ho, unang tung pamanganmu sandiri, halak sileban tagonan, unang bibirmu sandiri. Dokdok do batu, jala borat horsik, alai dumokdok sian duansa do anggo hamurhingon ni halak na oto.",
    },
    "text6": {
        "source": "Jaman dahulu hiduplah seorang raja yang Bernama Raja Rahat yang berkuasa di Samosir. Raja Rahat adalah raja yang dikenal rakyatnya sebagai raja yang bijaksana dan adil. Para rakyatnya pun senang memiliki raja seperti Raja Rahat. Raja Rahat juga memiliki permaisuri yang baik hati dan memiliki anak satu yang beri nama Manggale.",
        "target": "Na jolo adong ma raja na margoar Raja Rahat na marhuta i Samosir. Raja Rahattakkas do i tanda akka raiatna raja nabisuk jala natigor. Sonang do akka raiatna mangida raja Rahat on. Raja Rahat on mangarihon parsonduk bolon na tong marbasa roha jala mangarihon sada ianakhon na margoar Manggale.",
    },
}

translated_sentences = []

# Perform translation and evaluation for each test sentence
for key, text_dict in test_sentences.items():
    source_text, translation, correct_translation = text_dict["source"], "", text_dict["target"]

    # Translate the source text
    translated_text = translator(source_text, src_lang="ind_Latn", tgt_lang="btk_Latn")
    translation = translated_text[0]["translation_text"]

    # Calculate the SacreBLEU score
    sacrebleu_score = metric.compute(predictions=[translation], references=[[correct_translation]])
    sacrebleu_score = sacrebleu_score["score"]

    translated_sentences.append((source_text, translation, correct_translation, sacrebleu_score))

# Print the results
for i, (source, translation, correct_translation, sacrebleu_score) in enumerate(translated_sentences):
    print(f"Sentence {i + 1}:")
    print("Source Sentence: ", source)
    print("Translated Sentence: ", translation)
    print("Correct Translated Sentence: ", correct_translation)
    print("SacreBLEU Score: ", sacrebleu_score)
    print()

Sentence 1:
Source Sentence:  Turun disini lah kita.
Translated Sentence:  Get down here.
Correct Translated Sentence:  Turun dison ma hita.
SacreBLEU Score:  12.44023474812678

Sentence 2:
Source Sentence:  Ini pengalaman pertamaku.
Translated Sentence:  This is my first experience.
Correct Translated Sentence:  On ma pengalamanku na parjolo.
SacreBLEU Score:  8.116697886877475

Sentence 3:
Source Sentence:  Jika kamu pergi, hatiku akan pergi bersamamu.
Translated Sentence:  If you go, my heart will go with you.
Correct Translated Sentence:  Molo lao ho, rohakku dohot mai lao.
SacreBLEU Score:  4.456882760699063

Sentence 4:
Source Sentence:  Ketika menghadapi masalah apapun dalam kehidupan ini maka terimalah dengan hati yang sabar dan iman yang kuat.
Translated Sentence:  ️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️
Correct Translated Sentence:  Bahenma dirimu songon laut naluas , manang songon dia pe masalah naroh tungolumu, jalo ma dohot roha naserep dohot iman na gogo.
SacreBLEU Score:  0.0

Sentence 5:
Source Sentence:  Biarlah orang lain memuji engkau dan bukan mulutmu, orang yang tidak kau kenal dan bukan bibirmu sendiri. Batu adalah berat dan pasir pun ada beratnya, tetapi lebih berat dari kedua-duanya adalah sakit hati terhadap orang bodoh.
Translated Sentence:  Let another praise thee, and not thy mouth; a stranger, and not thy own lips. The stone is heavy, and the sand heavy; but more than these is the sorrow of the fool.
Correct Translated Sentence:  Halak na asing tagonan mamuji ho, unang tung pamanganmu sandiri, halak sileban tagonan, unang bibirmu sandiri. Dokdok do batu, jala borat horsik, alai dumokdok sian duansa do anggo hamurhingon ni halak na oto.
SacreBLEU Score:  1.3737889784665156

Sentence 6:
Source Sentence:  Jaman dahulu hiduplah seorang raja yang Bernama Raja Rahat yang berkuasa di Samosir. Raja Rahat adalah raja yang dikenal rakyatnya sebagai raja yang bijaksana dan adil. Para rakyatnya pun senang memiliki raja seperti Raja Rahat. Raja Rahat juga memiliki permaisuri yang baik hati dan memiliki anak satu yang beri nama Manggale.
Translated Sentence:  ️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️
Correct Translated Sentence:  Na jolo adong ma raja na margoar Raja Rahat na marhuta i Samosir. Raja Rahattakkas do i tanda akka raiatna raja nabisuk jala natigor. Sonang do akka raiatna mangida raja Rahat on. Raja Rahat on mangarihon parsonduk bolon na tong marbasa roha jala mangarihon sada ianakhon na margoar Manggale.
SacreBLEU Score:  0.0

In [ ]:
import locale
locale.getpreferredencoding = lambda: "UTF-8"

In [ ]:
! pip install bitsandbytes # For 'adamw_bnb_8bit' optimizer

Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.10/dist-packages (0.41.1)

In [ ]:
model

M2M100ForConditionalGeneration(
  (model): M2M100Model(
    (shared): Embedding(256206, 1024, padding_idx=1)
    (encoder): M2M100Encoder(
      (embed_tokens): Embedding(256206, 1024, padding_idx=1)
      (embed_positions): M2M100SinusoidalPositionalEmbedding()
      (layers): ModuleList(
        (0-11): 12 x M2M100EncoderLayer(
          (self_attn): M2M100Attention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (activation_fn): ReLU()
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
    (decoder): M2M100Decoder(
      (embed_tokens): Embedding(256206, 1024, padding_idx=1)
      (embed_positions): M2M100SinusoidalPositionalEmbedding()
      (layers): ModuleList(
        (0-11): 12 x M2M100DecoderLayer(
          (self_attn): M2M100Attention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (activation_fn): ReLU()
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (encoder_attn): M2M100Attention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (encoder_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
  )
  (lm_head): Linear(in_features=1024, out_features=256206, bias=False)
)

In [ ]:
from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer

training_args = Seq2SeqTrainingArguments(
    output_dir="indonesian_to_batak_toba_translation_model",
    evaluation_strategy="epoch",

    # Parameters to tune
    # ---
    learning_rate=5e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=16,
    weight_decay=0.3,
    num_train_epochs=5,
    warmup_ratio=0.1,
    # ---

    # For optimizing resources usage (GPU, RAM, etc.)
    # ---
    predict_with_generate=True,
    optim="adamw_bnb_8bit",
    fp16=True,
    push_to_hub=True,
    save_total_limit=3,
    eval_accumulation_steps=4,
    # ---
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.train()

TrainOutput(global_step=8250, training_loss=1.4149773393110796, metrics={'train_runtime': 6802.6101, 'train_samples_per_second': 4.851, 'train_steps_per_second': 1.213, 'total_flos': 4469653241856000.0, 'train_loss': 1.4149773393110796, 'epoch': 5.0})

In [ ]:
trainer.push_to_hub()

pytorch_model.bin:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

'https://huggingface.co/kepinsam/indonesian_to_bataknese_translation_model/tree/main/'

### Assessing the NLLB model **after/post** fine-tuning (with training on the Batak Toba dataset)

In [ ]:
from transformers import pipeline
import evaluate

translator = pipeline("translation", model="indonesian_to_batak_toba_translation_model")
metric = evaluate.load("sacrebleu")

test_sentences = {
    "text1": {
        "source": "Turun disini lah kita.",
        "target": "Turun dison ma hita.",
        },
    "text2": {
        "source": "Ini pengalaman pertamaku.",
        "target": "On ma pengalamanku na parjolo.",
    },
    "text3": {
        "source": "Jika kamu pergi, hatiku akan pergi bersamamu.",
        "target": "Molo lao ho, rohakku dohot mai lao.",
    },
    "text4": {
        "source": "Ketika menghadapi masalah apapun dalam kehidupan ini maka terimalah dengan hati yang sabar dan iman yang kuat.",
        "target": "Bahenma dirimu songon laut naluas , manang songon dia pe masalah naroh tungolumu, jalo ma dohot roha naserep dohot iman na gogo.",
    },
    "text5": {
        "source": "Biarlah orang lain memuji engkau dan bukan mulutmu, orang yang tidak kau kenal dan bukan bibirmu sendiri. Batu adalah berat dan pasir pun ada beratnya, tetapi lebih berat dari kedua-duanya adalah sakit hati terhadap orang bodoh.",
        "target": "Halak na asing tagonan mamuji ho, unang tung pamanganmu sandiri, halak sileban tagonan, unang bibirmu sandiri. Dokdok do batu, jala borat horsik, alai dumokdok sian duansa do anggo hamurhingon ni halak na oto.",
    },
    "text6": {
        "source": "Jaman dahulu hiduplah seorang raja yang Bernama Raja Rahat yang berkuasa di Samosir. Raja Rahat adalah raja yang dikenal rakyatnya sebagai raja yang bijaksana dan adil. Para rakyatnya pun senang memiliki raja seperti Raja Rahat. Raja Rahat juga memiliki permaisuri yang baik hati dan memiliki anak satu yang beri nama Manggale.",
        "target": "Na jolo adong ma raja na margoar Raja Rahat na marhuta i Samosir. Raja Rahattakkas do i tanda akka raiatna raja nabisuk jala natigor. Sonang do akka raiatna mangida raja Rahat on. Raja Rahat on mangarihon parsonduk bolon na tong marbasa roha jala mangarihon sada ianakhon na margoar Manggale.",
    },
}

translated_sentences = []

# Perform translation and evaluation for each test sentence
for key, text_dict in test_sentences.items():
    source_text, translation, correct_translation = text_dict["source"], "", text_dict["target"]

    # Translate the source text
    translated_text = translator(source_text, src_lang="ind_Latn", tgt_lang="btk_Latn")
    translation = translated_text[0]["translation_text"]

    # Calculate the SacreBLEU score
    sacrebleu_score = metric.compute(predictions=[translation], references=[[correct_translation]])
    sacrebleu_score = sacrebleu_score["score"]

    translated_sentences.append((source_text, translation, correct_translation, sacrebleu_score))

# Print the results
for i, (source, translation, correct_translation, sacrebleu_score) in enumerate(translated_sentences):
    print(f"Sentence {i + 1}:")
    print("Source Sentence: ", source)
    print("Translated Sentence: ", translation)
    print("Correct Translated Sentence: ", correct_translation)
    print("SacreBLEU Score: ", sacrebleu_score)
    print()

Sentence 1:
Source Sentence:  Turun disini lah kita.
Translated Sentence:  Turun dison ma hita.
Correct Translated Sentence:  Turun dison ma hita.
SacreBLEU Score:  100.00000000000004

Sentence 2:
Source Sentence:  Ini pengalaman pertamaku.
Translated Sentence:  on pengalaman pertama ku.
Correct Translated Sentence:  On ma pengalamanku na parjolo.
SacreBLEU Score:  8.745825313180626

Sentence 3:
Source Sentence:  Jika kamu pergi, hatiku akan pergi bersamamu.
Translated Sentence:  Molo lao ho, rohaku laho dohot ho.
Correct Translated Sentence:  Molo lao ho, rohakku dohot mai lao.
SacreBLEU Score:  33.03164318013809

Sentence 4:
Source Sentence:  Ketika menghadapi masalah apapun dalam kehidupan ini maka terimalah dengan hati yang sabar dan iman yang kuat.
Translated Sentence:  hatia mangadopi masalah ahape dalam hidup on maka terima ma rap hati na sabar rap iman na gogo.
Correct Translated Sentence:  Bahenma dirimu songon laut naluas , manang songon dia pe masalah naroh tungolumu, jalo ma dohot roha naserep dohot iman na gogo.
SacreBLEU Score:  10.780498689427162

Sentence 5:
Source Sentence:  Biarlah orang lain memuji engkau dan bukan mulutmu, orang yang tidak kau kenal dan bukan bibirmu sendiri. Batu adalah berat dan pasir pun ada beratnya, tetapi lebih berat dari kedua-duanya adalah sakit hati terhadap orang bodoh.
Translated Sentence:  Asa di puji ho jolma na asing jala dang di sungkun mu, jolma na dang di boto ho jala dang di bibirmu sandiri. Batu borat jala pasir pe adong boratna, alai lobi borat sian nadua-dua ima hatcit roha tu jolma oto.
Correct Translated Sentence:  Halak na asing tagonan mamuji ho, unang tung pamanganmu sandiri, halak sileban tagonan, unang bibirmu sandiri. Dokdok do batu, jala borat horsik, alai dumokdok sian duansa do anggo hamurhingon ni halak na oto.
SacreBLEU Score:  5.690652718430211